version: '3'

services:
  frontend:
    build: ./frontend
    container_name: react-app
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-networks


  backend:
    build: ./backend
    container_name: node-api
    ports:
      - '5000:5000'
    restart: always
    networks:
      - mern-networks

networks:
  mern-networks:
    driver: bridge
